### ISSUE TITLE
New fields for window object are not deep copied on assignment

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Fission#100]
Consider this example where:
```
var obj = {a: {b: 1}}
window.obj = obj
window.obj.a.b
```
This fails because the call to `window.obj.a` returns `undefined`.

**Comment by arjunguha** [comment]
Now that we have HeapValues factored out, why don't you do this: create a new HeapValue exclusively for Window, and do whatever you need to do make it work. :)

**Comment by rachitnigam** [comment]
The issue with the hack mentioned:

1. Whenever there is a `.get` call on this new Window HeapValue for a field that the native js window holds, fission tries to convert it to a JS value. A simple solution (one that doesn't work either) is to just send in the underlying native window in as the JS value. This still doesn't work (for some reason).

2. Apart from the above problem, for some reason window.setTimeout also doesn't seem to be working with the hack because of the same reason.

3. `hasOwnProperty` still doesn't work because of the VObj issue mentioned in #126.

**Comment by rachitnigam** [comment]
I figured out why `window.setTimeout` or `hasOwnProperty` won't work. It is because because fission tries to convert the implicit "this" in all functions and this is bound to the (Fission) Window Object which cannot be converted to JS.

This can be solved by converting everything that is stored on the Fission object using an FFI similar to objConversion but it will have the same security issues.

**Comment by arjunguha** [comment]
This is fixed, right?

**Comment by rachitnigam** [comment]
Yes, we added this test in the last merge: https://github.com/plasma-umass/Fission/blob/master/js/src/test/scala/BrowserTestSuite3.scala#L75
