### ISSUE TITLE
.split on strings throws exception

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Fission#32]
Running `.split` method on strings throw the following error:

`java.lang.IllegalStateException: WebSocket is closed`

Is this expected behavior?

**Comment by arjunguha** [comment]
no. What printed in fission.log?

**Comment by rolivia** [comment]
Not surprising.  Method calls expect the target to be an object, not a string.  Should just need a special case for method calls where the target is a string and then do the method call in JS etc.

**Comment by rachitnigam** [comment]
I see.
