### ISSUE TITLE
Named function assigned to variable

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Fission#96]
The following errors:
```
var p = function foo(x) { return x; }
p(1)
```
with `foo not defined`.

This does not:
```
var p = function(x) {return x; }
p(1)
```

Quick fix would be to drop the name, but not sure if that is semantically consistent with JS.

**Comment by arjunguha** [comment]
Right, the fix is also a hack. Let's figure out what is happening and do it right.

**Comment by rachitnigam** [comment]
The desugarer transforms the code to:
```
var p = undefined;
p = (foo = <fundef>)
```
At this point, foo is undefined, causing the error.

**Comment by rachitnigam** [comment]
This also fails: 
```
function makeIden() {
  return function id(x) { return x; }
}
var foo = makeIden();
foo(1)
```
with `id was not defined`. Imagine this is for similar reasons.
